//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.09 at 10:09:03 ¤U¤È CST 
//


package ntut.csie.samt.aaprofile.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AAProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AAProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Accounts" type="{jaxb.aaprofile.manager.samt.csie.ntut}Accounts" minOccurs="0"/>
 *         &lt;element name="Groups" type="{jaxb.aaprofile.manager.samt.csie.ntut}Groups" minOccurs="0"/>
 *         &lt;element name="Permissions" type="{jaxb.aaprofile.manager.samt.csie.ntut}Permissions" minOccurs="0"/>
 *         &lt;element name="FolderList" type="{jaxb.aaprofile.manager.samt.csie.ntut}FolderList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AAProfile", propOrder = {
    "accounts",
    "groups",
    "permissions",
    "folderList"
})
public class AAProfile {

    @XmlElement(name = "Accounts")
    protected Accounts accounts;
    @XmlElement(name = "Groups")
    protected Groups groups;
    @XmlElement(name = "Permissions")
    protected Permissions permissions;
    @XmlElement(name = "FolderList")
    protected FolderList folderList;

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link Accounts }
     *     
     */
    public Accounts getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accounts }
     *     
     */
    public void setAccounts(Accounts value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link Groups }
     *     
     */
    public Groups getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link Groups }
     *     
     */
    public void setGroups(Groups value) {
        this.groups = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link Permissions }
     *     
     */
    public Permissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Permissions }
     *     
     */
    public void setPermissions(Permissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the folderList property.
     * 
     * @return
     *     possible object is
     *     {@link FolderList }
     *     
     */
    public FolderList getFolderList() {
        return folderList;
    }

    /**
     * Sets the value of the folderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderList }
     *     
     */
    public void setFolderList(FolderList value) {
        this.folderList = value;
    }

}
