//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.09 at 10:09:03 ¤U¤È CST 
//


package ntut.csie.samt.aaprofile.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ntut.csie.samt.manager.aaprofile.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AAProfile_QNAME = new QName("jaxb.aaprofile.manager.samt.csie.ntut", "AAProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ntut.csie.samt.manager.aaprofile.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Accounts }
     * 
     */
    public Accounts createAccounts() {
        return new Accounts();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link PathMember }
     * 
     */
    public PathMember createPathMember() {
        return new PathMember();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

    /**
     * Create an instance of {@link FolderList }
     * 
     */
    public FolderList createFolderList() {
        return new FolderList();
    }

    /**
     * Create an instance of {@link GroupMember }
     * 
     */
    public GroupMember createGroupMember() {
        return new GroupMember();
    }

    /**
     * Create an instance of {@link Permissions }
     * 
     */
    public Permissions createPermissions() {
        return new Permissions();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link AAProfile }
     * 
     */
    public AAProfile createAAProfile() {
        return new AAProfile();
    }

    /**
     * Create an instance of {@link Groups }
     * 
     */
    public Groups createGroups() {
        return new Groups();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AAProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "jaxb.aaprofile.manager.samt.csie.ntut", name = "AAProfile")
    public JAXBElement<AAProfile> createAAProfile(AAProfile value) {
        return new JAXBElement<AAProfile>(_AAProfile_QNAME, AAProfile.class, null, value);
    }

}
