//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.09 at 10:09:03 ¤U¤È CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "jaxb.aaprofile.manager.samt.csie.ntut", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ntut.csie.samt.aaprofile.jaxb;
